motd_info:
  - " FQDN:    ": "{{ ansible_fqdn }}"
  - " Distro:  ": "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  - " Virtual: ": "{{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}\n"
  - " CPUs:    ": "{{ ansible_processor_vcpus }}"
  - " RAM:     ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"
  - " More info:     ": "https://github.com/stobias123/vagrant-dev-box"
pip_install_packages:
  - awscli
#  - molecule
#  - f5-sdk
  - pyvmomi
  - pywinrm
#  - netapp-lib
