- hosts: all
  become: yes
  vars:
    docker_users:
      - vagrant
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - secfigo.terraform
    - ansible-role-perforce
    - ansible-motd
    - ansible-go
